export const ABOUT: string = 'About'
export const CONSULTATION: string = 'Consultation'
export const MAKE_SOFTWARE: string = 'Make software'
export const PORTFOLIO: string = 'Portfolio'
export const RATHER_THAN_DELIVERING_A_BLACKBOX: string = 'Rather than delivering a software “blackbox”, SetLife’s solutions engineering process features thoughtful guidance and detailed documentation so you can develop & maintain your project in the future (with or without us!)'
export const SERVICES: string = 'Services'
export const SERVICE_PACKAGES: string = 'Service Packages'
export const SETLIFE = 'setlife'
export const SOLUTIONS = 'solutions'
export const YOUR_SUPERPOWER: string = 'your superpower'

export const SEE_MORE = 'See More'