export const MAKE_SOFTWARE = 'Make software'
export const SERVICES: string = 'Services'
export const YOUR_SUPERPOWER = 'your superpower'
export const RATHER_THAN_DELIVERING_A_BLACKBOX = 'Rather than delivering a software “blackbox”, SetLife’s solutions engineering process features thoughtful guidance and detailed documentation so you can develop & maintain your project in the future (with or without us!)'
export const SEE_MORE = 'See More'